### ISSUE TITLE
Show page not working for any uploaded asset

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geoblacklight_admin#77]
Process:

1. Go to Admin Tools - Assets
2. Select "Show" for any asset.
3. Error: `500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.`

**Comment by ewlarson** [comment]
Just got home. I'll take a look at this ASAP.

**Comment by karenmajewicz** [comment]
No hurry! It's the internal show page that isn't working and I am just working on dev.

**Comment by ewlarson** [comment]
Troubleshooting. This page is erroring with...

```
F, [2024-09-08T08:48:30.662495 #1144647] FATAL -- : [cc991234-887e-4f31-b352-7fe1779d20fd]   
[cc991234-887e-4f31-b352-7fe1779d20fd] ActionView::Template::Error (undefined method `file_url' for true):
[cc991234-887e-4f31-b352-7fe1779d20fd]     32:         <th>Asset Link</th>
[cc991234-887e-4f31-b352-7fe1779d20fd]     33:         <td><%= link_to "Asset Link", @asset.file.url %></td>
[cc991234-887e-4f31-b352-7fe1779d20fd]     34:       </tr>
[cc991234-887e-4f31-b352-7fe1779d20fd]     35:       <% if thumb_to_render?(@asset) %>
[cc991234-887e-4f31-b352-7fe1779d20fd]     36:         <tr>
[cc991234-887e-4f31-b352-7fe1779d20fd]     37:           <th>Thumbnail</th>
[cc991234-887e-4f31-b352-7fe1779d20fd]     38:           <td><%= image_tag(@asset.file_url(:thumb_standard_2X)) %></td>
[cc991234-887e-4f31-b352-7fe1779d20fd]   
[cc991234-887e-4f31-b352-7fe1779d20fd] geoblacklight_admin (2f64866b128a) app/helpers/document_helper.rb:62:in `thumb_to_render?'
[cc991234-887e-4f31-b352-7fe1779d20fd] geoblacklight_admin (2f64866b128a) app/views/admin/assets/show.html.erb:35
[cc991234-887e-4f31-b352-7fe1779d20fd] actionview (7.0.8.4) lib/action_view/base.rb:244:in `public_send'
```
